import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "../app/components/sessionProvider/SessionProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { AuthButton } from "./components/authButton/AuthButton";
import Link from "next/link";
import Logout from "./components/logOut/Logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  if (!session) {
    redirect("/register");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {!!session && <Logout />} {!session && <span>Login</span>}
        </nav>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
